version: '3.7'

services:
  subscriber1:
    image: 'sarychev90/solace:consumer'
    build:
       context: .
       dockerfile: ./solaceJmsConsumer/Dockerfile
    ports:
      - 9071:8070
    container_name: subscriber1
    depends_on:
      - publisher
  subscriber2:
    image: 'sarychev90/solace:consumer'
    build:
       context: .
       dockerfile: ./solaceJmsConsumer/Dockerfile
    ports:
      - 9072:8070
    container_name: subscriber2
    depends_on:
      - publisher
  subscriber3:
    image: 'sarychev90/solace:consumer'
    build:
       context: .
       dockerfile: ./solaceJmsConsumer/Dockerfile
    ports:
      - 9073:8070
    container_name: subscriber3 
    depends_on:
      - publisher
  publisher:
    image: 'sarychev90/solace:produser'
    build:
       context: .
       dockerfile: ./solaceJmsProduser/Dockerfile
    ports:
      - 9090:8090
    container_name: publisher
    depends_on:
      - solace
  solace:
    image: 'solace/solace-pubsub-standard:latest'
    container_name: solace
    shm_size: '2gb'
    ports:
      - 8080:8080
      - 55555:55555
      - 8008:8008
      - 1884:1883
      - 8000:8000
      - 5672:5672
      - 9000:9000
      - 2222:2222
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin


     